### ISSUE TITLE
Need clarification 

### ISSUE THREAD

**Issue by ktownsend-personal** [onlyoneme/home-assistant-custom-components-wiim#7]
I really just want to ask a question, but can’t figure out where to do that. 

Is this fork necessary for a Wiim Mini or can the original project be used? It seems like the Wiim Mini is based on LinkPlay A31 that the original integration targets, so what does this fork do differently?

It might be worth adding clarification to the README intro.  

Thanks.

**Comment by onlyoneme** [comment]
It's for Mini and beta branch has got a support for Pro so it can handle whole WiiM brand.
Mini is not A31 based that's why this fork has been created. Original project uses http port to communicate to the devices while WiiM requires https communication. There are also other differences in http api implementation.
In theory it could work with other Linkplay devices as long as they support https communication.

**Comment by ktownsend-personal** [comment]
Thanks. I must have found an incorrect association of Wiim Mini with A31 online. If it’s not A31 based, do you know what it is based on?

**Comment by ktownsend-personal** [comment]
I finally found a reference mentioning A97. Now I’m going down the rabbit hole looking for API references because I’m curious. 😊

**Comment by onlyoneme** [comment]
> I finally found a reference mentioning A97. Now I’m going down the rabbit hole looking for API references because I’m curious. 😊

It's not exactly A97 as Mini has a custom PCB but it seems to be the closest .

**Comment by ktownsend-personal** [comment]
The article I saw basically said it is a re-implementation of the A97 due to form factor being smaller, which I took to mean functional equivalent but I’m not surprised there might be API differences.
